// GENERATED by videopowers:mg-layout — regenerated by `layout apply`; do not hand-edit.
// (Template placeholder — empty until the mg-layout pass runs. FootageStage
// renders plain fullscreen footage while this is empty.)

export type ShotKind = "FULLFACE" | "OVERLAY" | "SPLIT" | "BUBBLE" | "FULLGRAPHICS" | "CHAPTER";
export type ShotContent = "none" | "graphics" | "media";

export interface Shot {
  id: string;
  chapterId: string;
  origin: "yaml" | "auto-lead" | "chapter-card";
  tag: string;
  kind: ShotKind;
  content: ShotContent;
  cells: number[];
  side: "left" | "right" | null;
  facePct: number | null;
  shape: "circle" | "rect" | null;
  startFrame: number;
  durationInFrames: number;
  purpose: string | null;
  subjects: string[];
  builds: { word: string; frame: number }[];
  cardTitle: string | null;
}

export const SHOTS: Shot[] = [];
