import { execFile } from "node:child_process";
import { existsSync } from "node:fs";
import { copyFile, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { promisify } from "node:util";
import type { BeatSheet, Word } from "./types.js";

const pexec = promisify(execFile);
const GENERATED_HEADER = (what: string) =>
  `// GENERATED by videopowers:mg-setup (${what}) — regenerated on re-run; do not hand-edit.\n`;

export interface ScaffoldResult {
  copied: string[];
  skipped: string[];
  generated: string[];
}

/**
 * Copy the template into the project dir. Existing files are left alone
 * unless `force` — a plain re-run never touches files the user may have
 * edited. Generated files are handled separately (always rewritten).
 */
export async function copyTemplate(templateDir: string, dest: string, force: boolean): Promise<ScaffoldResult> {
  const result: ScaffoldResult = { copied: [], skipped: [], generated: [] };
  const walk = async (dir: string): Promise<void> => {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      if (entry.name === "node_modules" || entry.name === ".DS_Store") continue;
      const src = join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(src);
        continue;
      }
      const rel = relative(templateDir, src);
      const target = join(dest, rel);
      if (existsSync(target) && !force) {
        result.skipped.push(rel);
        continue;
      }
      await mkdir(dirname(target), { recursive: true });
      await copyFile(src, target);
      result.copied.push(rel);
    }
  };
  await walk(templateDir);
  return result;
}

/** Set the scaffolded project's package name to the video's slug. */
export async function patchPackageName(dest: string, slug: string): Promise<void> {
  const path = join(dest, "package.json");
  const pkg = JSON.parse(await readFile(path, "utf8")) as Record<string, unknown>;
  pkg.name = `${slug}-remotion`;
  await writeFile(path, JSON.stringify(pkg, null, 2) + "\n");
}

/** Render the generated chapters.ts from the beat sheet. */
export function renderChaptersTs(sheet: BeatSheet): string {
  const rows = sheet.chapters
    .map(
      (c) =>
        `  { id: ${JSON.stringify(c.id)}, number: ${c.number}, title: ${JSON.stringify(c.title)}, ` +
        `displayName: ${JSON.stringify(c.displayName)}, startSec: ${c.startSec}, endSec: ${c.endSec}, ` +
        `startFrame: ${c.startFrame}, durationInFrames: ${c.durationInFrames}, gapAfterSec: ${c.gapAfterSec} },`,
    )
    .join("\n");
  return (
    GENERATED_HEADER("chapters") +
    `
export interface Chapter {
  id: string;
  number: number;
  title: string;
  displayName: string;
  startSec: number;
  endSec: number;
  startFrame: number;
  durationInFrames: number;
  gapAfterSec: number;
}

export const CHAPTERS: Chapter[] = [
${rows}
];
`
  );
}

/** Render the generated video.config.ts. */
export function renderVideoConfigTs(sheet: BeatSheet): string {
  return (
    GENERATED_HEADER("video config") +
    `
export const VIDEO = {
  slug: ${JSON.stringify(sheet.slug)},
  title: ${JSON.stringify(sheet.title)},
  fps: ${sheet.fps},
  width: ${sheet.width},
  height: ${sheet.height},
  durationInFrames: ${sheet.durationInFrames},
} as const;
`
  );
}

export async function writeGenerated(
  dest: string,
  sheet: BeatSheet,
  words: Word[],
  source: Record<string, unknown>,
): Promise<string[]> {
  const files: Array<[string, string]> = [
    ["src/chapters.ts", renderChaptersTs(sheet)],
    ["src/video.config.ts", renderVideoConfigTs(sheet)],
    ["src/data/beat-sheet.json", JSON.stringify(sheet, null, 2) + "\n"],
    ["src/data/words.json", JSON.stringify(words) + "\n"],
    ["src/data/source.json", JSON.stringify(source, null, 2) + "\n"],
  ];
  for (const [rel, content] of files) {
    const path = join(dest, rel);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content);
  }
  return files.map(([rel]) => rel);
}

async function run(cmd: string, args: string[], cwd: string): Promise<void> {
  try {
    await pexec(cmd, args, { cwd, maxBuffer: 1024 * 1024 * 64 });
  } catch (e) {
    const err = e as { stdout?: string; stderr?: string };
    const tail = `${String(err.stdout ?? "")}\n${String(err.stderr ?? "")}`.split("\n").filter(Boolean).slice(-15).join("\n");
    throw new Error(`'${cmd} ${args.join(" ")}' failed in ${cwd}:\n${tail}`);
  }
}

/** pnpm install (workspace-independent) + tsc --noEmit as the boot check. */
export async function installAndCheck(dest: string): Promise<void> {
  await run("pnpm", ["install", "--ignore-workspace"], dest);
  await run("pnpm", ["exec", "tsc", "--noEmit"], dest);
}
