// GENERATED by videopowers:mg-setup (chapters) — regenerated on re-run; do not hand-edit.
// (Template placeholder — mg-setup overwrites this with the video's real chapters.)

export interface Chapter {
  id: string;
  number: number;
  title: string;
  displayName: string;
  startSec: number;
  endSec: number;
  startFrame: number;
  durationInFrames: number;
  gapAfterSec: number;
}

export const CHAPTERS: Chapter[] = [
  { id: "ch01-template", number: 1, title: "TEMPLATE", displayName: "01 · TEMPLATE", startSec: 0, endSec: 10, startFrame: 0, durationInFrames: 300, gapAfterSec: 0 },
];
