// GENERATED by videopowers:mg-setup (video config) — regenerated on re-run; do not hand-edit.
// (Template placeholder — mg-setup overwrites this with the video's real config.)

export const VIDEO = {
  slug: "template",
  title: "Template",
  fps: 30,
  width: 1920,
  height: 1080,
  durationInFrames: 300,
} as const;
