import type { BeatSheet, ResolvedShot } from "./types.js";

const HEADER = "// GENERATED by videopowers:mg-layout — regenerated by `layout apply`; do not hand-edit.\n";

/** shots.ts — what FootageStage renders. Keep the type local to the video project. */
export function renderShotsTs(shots: ResolvedShot[]): string {
  const rows = shots
    .map((s) => "  " + JSON.stringify({
      id: s.id,
      chapterId: s.chapterId,
      origin: s.origin,
      tag: s.tag,
      kind: s.spec.kind,
      content: s.spec.content,
      cells: s.spec.cells,
      side: s.spec.side,
      facePct: s.spec.facePct,
      shape: s.spec.shape,
      startFrame: s.startFrame,
      durationInFrames: s.durationInFrames,
      purpose: s.purpose,
      subjects: s.subjects,
      builds: s.builds.map((b) => ({ word: b.word, frame: b.frame })),
      cardTitle: s.cardTitle,
    }) + ",")
    .join("\n");
  return `${HEADER}
export type ShotKind = "FULLFACE" | "OVERLAY" | "SPLIT" | "BUBBLE" | "FULLGRAPHICS" | "CHAPTER";
export type ShotContent = "none" | "graphics" | "media";

export interface Shot {
  id: string;
  chapterId: string;
  origin: "yaml" | "auto-lead" | "chapter-card";
  tag: string;
  kind: ShotKind;
  content: ShotContent;
  cells: number[];
  side: "left" | "right" | null;
  facePct: number | null;
  shape: "circle" | "rect" | null;
  startFrame: number;
  durationInFrames: number;
  purpose: string | null;
  subjects: string[];
  builds: { word: string; frame: number }[];
  cardTitle: string | null;
}

export const SHOTS: Shot[] = [
${rows}
];
`;
}

function fmtTime(sec: number): string {
  const m = Math.floor(sec / 60);
  return `${m}:${(sec - m * 60).toFixed(1).padStart(4, "0")}`;
}

/** layout.md — the human table view, one section per chapter. */
export function renderLayoutMd(shots: ResolvedShot[], sheet: BeatSheet): string {
  const lines: string[] = [
    "# Layout pass (generated view — edit layout.yaml, then `layout apply`)",
    "",
    `Video: ${sheet.title} · ${fmtTime(sheet.durationSec)} · ${sheet.fps}fps`,
    "",
  ];
  for (const ch of sheet.chapters) {
    lines.push(`## ${ch.displayName}`);
    lines.push("");
    lines.push("| Shot | Span | Layout | Anchor | Purpose |");
    lines.push("|---|---|---|---|---|");
    for (const s of shots.filter((x) => x.chapterId === ch.id)) {
      const span = `${fmtTime(s.startSec)}–${fmtTime(s.endSec)}`;
      const builds = s.builds.length > 0 ? `<br>builds: ${s.builds.map((b) => `"${b.word}"`).join(", ")}` : "";
      lines.push(
        `| ${s.id} | ${span} | \`${s.tag}\` | "${s.anchorText}" | ${(s.purpose ?? "—").replace(/\|/g, "\\|")}${builds} |`,
      );
    }
    lines.push("");
  }
  return lines.join("\n");
}

/** media-shots.md — the capture to-do list for the human, before mg-visuals. */
export function renderMediaShotsMd(shots: ResolvedShot[]): string {
  const media = shots.filter((s) => s.spec.content === "media" && s.origin === "yaml");
  const lines: string[] = [
    "# Media to capture (generated — every `media` shot in layout.yaml)",
    "",
    "These do not exist until someone records them. Capture before mg-visuals.",
    "",
  ];
  if (media.length === 0) {
    lines.push("Nothing — no media shots in this layout.");
    return lines.join("\n") + "\n";
  }
  for (const s of media) {
    lines.push(`- [ ] **${s.id}** (${fmtTime(s.startSec)}–${fmtTime(s.endSec)}, \`${s.tag}\`)`);
    lines.push(`      ${s.purpose ?? ""}`);
    if (s.subjects.length > 0) lines.push(`      subjects: ${s.subjects.join(", ")}`);
  }
  return lines.join("\n") + "\n";
}
